SELECT 
FP.PRODUCT_ID AS PRODUCT_ID,
FP.PRODUCT_NAME AS PRODUCT_NAME,
(FP.PRICE * SUB.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
INNER JOIN (
    SELECT 
    FO.PRODUCT_ID,
    SUM (FO.AMOUNT) AS AMOUNT
    FROM
    FOOD_ORDER AS FO
    WHERE PRODUCE_DATE LIKE '2022-05-%'
    GROUP BY PRODUCT_ID
) AS SUB
ON FP.PRODUCT_ID = SUB.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;