SELECT
MP.MEMBER_NAME AS MEMBER_NAME,
SUB.REVIEW_TEXT AS REVIEW_TEXT,
DATE_FORMAT(SUB.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
INNER JOIN (
    SELECT * 
    FROM REST_REVIEW AS RR
    INNER JOIN (
        SELECT 
            RR.MEMBER_ID AS ID, 
            COUNT(MEMBER_ID) AS COUNT
        FROM REST_REVIEW AS RR
        GROUP BY RR.MEMBER_ID
        ORDER BY COUNT DESC
        LIMIT 1
    ) AS SUB1
    ON RR.MEMBER_ID = SUB1.ID
) AS SUB
ON MP.MEMBER_ID = SUB.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;