WITH RECURSIVE TIMETABLE (HOUR) AS (
    SELECT 0
    UNION
    SELECT HOUR + 1 FROM TIMETABLE WHERE HOUR < 23
)

SELECT 
HOUR,
COUNT(AO.ANIMAL_ID) AS COUNT
FROM TIMETABLE AS TT
LEFT JOIN ANIMAL_OUTS AS AO
ON TT.HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;