SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, MAX_LENGTH AS LENGTH
FROM FISH_INFO AS FI
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
) AS SUB
ON FI.FISH_TYPE = SUB.FISH_TYPE
AND FI.LENGTH = SUB.MAX_LENGTH
JOIN FISH_NAME_INFO AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE;